name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - run: sudo apt-get install clang-tidy clang-tools
      - uses: actions/checkout@v2
      - name: Build and run tests
        run: bash travis.sh -xe
      - name: Build annotations
        if: always()
        uses: yuzutech/annotations-action@v0.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title: annotations (build)
          input: diagnostics.json
      - name: clang-tidy annotations
        if: always()
        uses: yuzutech/annotations-action@v0.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title: annotations (clang-tidy)
          input: tidy-annotations.json